// <auto-generated />
using Heroes.DAO;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Heroes.Migrations
{
    [DbContext(typeof(HeroDbContext))]
    [Migration("20200917013541_heroesandvillainsinit")]
    partial class heroesandvillainsinit
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8");

            modelBuilder.Entity("Heroes.Models.HeroesModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("heroName")
                        .HasColumnType("TEXT");

                    b.Property<string>("howToReach")
                        .HasColumnType("TEXT");

                    b.Property<string>("power")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("heroes");
                });

            modelBuilder.Entity("Heroes.Models.VillainsModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("howToReach")
                        .HasColumnType("TEXT");

                    b.Property<string>("power")
                        .HasColumnType("TEXT");

                    b.Property<string>("villainName")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("villains");
                });
#pragma warning restore 612, 618
        }
    }
}
